package dev.syndata.insert;

import dev.syndata.model.ColumnModel;
import dev.syndata.model.DataSetModel;
import dev.syndata.model.SchemaModel;
import dev.syndata.model.TableDataModel;
import dev.syndata.model.TableModel;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Types;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class SqlScriptExporterTest {

    @TempDir
    Path dir;

    private static ColumnModel col(String name, String type, int jdbcType) {
        return new ColumnModel(name, type, jdbcType, true);
    }

    @Test
    void rendersLiteralsByType() {
        assertEquals("NULL", SqlScriptExporter.render(col("x", "varchar", Types.VARCHAR), null, false));
        assertEquals("'it''s'", SqlScriptExporter.render(col("x", "varchar", Types.VARCHAR), "it's", false));
        assertEquals("12.30", SqlScriptExporter.render(col("x", "numeric", Types.NUMERIC),
                new BigDecimal("12.30"), false));
        assertEquals("true", SqlScriptExporter.render(col("x", "bool", Types.BOOLEAN), true, false));
        assertEquals("'\\x0102'", SqlScriptExporter.render(col("x", "bytea", Types.BINARY), "AQI=", false));
        assertEquals("(select real_id from _syndata_ids where local_id = -7)",
                SqlScriptExporter.render(col("id", "int8", Types.BIGINT), -7L, true));
        assertEquals("42", SqlScriptExporter.render(col("id", "int8", Types.BIGINT), 42L, true));
    }

    @Test
    void writesTransactionalScriptWithIdAllocation() throws Exception {
        SchemaModel schema = new SchemaModel();
        schema.schemaName = "public";
        TableModel t = new TableModel("public", "customers");
        ColumnModel id = new ColumnModel("id", "int8", Types.BIGINT, false);
        id.sequence = "public.hibernate_sequence";
        t.columns.add(id);
        t.columns.add(new ColumnModel("name", "varchar", Types.VARCHAR, false));
        t.primaryKey.add("id");
        schema.tables.add(t);

        DataSetModel data = new DataSetModel();
        TableDataModel td = new TableDataModel("public", "customers");
        td.columns = List.of("id", "name");
        td.rows.add(Arrays.asList(-1L, "Ada"));
        td.rows.add(Arrays.asList(-2L, "Grace"));
        data.tables.add(td);

        Path out = dir.resolve("load.sql");
        int rows = new SqlScriptExporter(schema, data).export(out);
        String sql = Files.readString(out);

        assertEquals(2, rows);
        assertTrue(sql.startsWith("-- Generated by syndata"));
        assertTrue(sql.contains("begin;"));
        assertTrue(sql.contains("create temporary table _syndata_ids"));
        assertTrue(sql.contains("nextval('\"public\".\"hibernate_sequence\"')"));
        assertTrue(sql.contains("unnest(array[-1,-2])"));
        assertTrue(sql.contains("insert into \"public\".\"customers\" (\"id\", \"name\") values"));
        assertTrue(sql.contains("(select real_id from _syndata_ids where local_id = -1), 'Ada'"));
        assertTrue(sql.trim().endsWith("commit;"));
    }
}
