// Generated by tools/build.py — do not edit by hand.
window.CASE = {
 "title": "The Nocturne Tapes",
 "reels": [
  {
   "n": 1,
   "title": "Sign-Off",
   "sub": "31 October 1957, 22:49"
  },
  {
   "n": 2,
   "title": "The Foley Room",
   "sub": "Eleven feet by nine, no window"
  },
  {
   "n": 3,
   "title": "Party Line",
   "sub": "Three conversations, one wire"
  },
  {
   "n": 4,
   "title": "Backward",
   "sub": "They only imagined tape going one direction"
  },
  {
   "n": 5,
   "title": "Nocturne",
   "sub": "Eleven minutes"
  }
 ],
 "cards": [
  {
   "id": "c_arch_open",
   "reel": 1,
   "title": "A voice on reel one",
   "sub": "No return address",
   "audio": "tape_arch_open",
   "kind": "tape",
   "dur": 94.46,
   "img": "assets/img/c_arch_open.webp"
  },
  {
   "id": "c_console",
   "reel": 1,
   "title": "How the console works",
   "sub": "The Archivist",
   "audio": "tape_arch_console",
   "kind": "tape",
   "dur": 62.46,
   "img": "assets/img/c_console.webp"
  },
  {
   "id": "c_broadcast",
   "reel": 1,
   "title": "The last broadcast",
   "sub": "31 Oct 1957 \u00b7 22:49 \u00b7 STEREO",
   "audio": "tape_broadcast",
   "kind": "tape",
   "dur": 118.83,
   "img": "assets/img/c_broadcast.webp"
  },
  {
   "id": "c_index",
   "reel": 1,
   "title": "Effects index",
   "sub": "D. Vance, read for the file",
   "audio": "tape_index",
   "kind": "tape",
   "dur": 87.77,
   "img": "assets/img/c_index.webp"
  },
  {
   "id": "c_warped",
   "reel": 1,
   "title": "Reel 4B \u2014 DAMAGED",
   "sub": "Recovered from the studio floor",
   "audio": "tape_warped",
   "kind": "tape",
   "dur": 14.21,
   "img": "assets/img/c_warped.webp"
  },
  {
   "id": "c_eddie",
   "reel": 1,
   "title": "Statement: E. Ferris",
   "sub": "Board engineer",
   "audio": "tape_eddie",
   "kind": "tape",
   "dur": 64.5,
   "img": "assets/img/c_eddie.webp"
  },
  {
   "id": "c_halligan",
   "reel": 1,
   "title": "Case 441-57",
   "sub": "Det. Sgt. Halligan",
   "audio": "tape_halligan",
   "kind": "tape",
   "dur": 53.76,
   "img": "assets/img/c_halligan.webp"
  },
  {
   "id": "c_arch_r2",
   "reel": 2,
   "title": "Reel two",
   "sub": "The Archivist",
   "audio": "tape_arch_r2",
   "kind": "tape",
   "dur": 57.84,
   "img": "assets/img/c_arch_r2.webp"
  },
  {
   "id": "c_dot_int",
   "reel": 2,
   "title": "Interview: D. Vance",
   "sub": "Foley artist",
   "audio": "tape_dot_interview",
   "kind": "tape",
   "dur": 52.95,
   "img": "assets/img/c_dot_int.webp"
  },
  {
   "id": "c_scene88",
   "reel": 2,
   "title": "Nocturne, ep. 88 sc. 3",
   "sub": "Rehearsal pass \u2014 effects only",
   "audio": "tape_scene88",
   "kind": "tape",
   "dur": 26.04,
   "img": "assets/img/c_scene88.webp"
  },
  {
   "id": "c_scene88x",
   "reel": 2,
   "title": "Ep. 88 sc. 3 \u2014 AS TRANSMITTED",
   "sub": "Six elements, not five",
   "audio": "tape_scene88x",
   "kind": "tape",
   "dur": 57.1,
   "img": "assets/img/c_scene88x.webp"
  },
  {
   "id": "c_iris",
   "reel": 2,
   "title": "Audition slate: I. Bell",
   "sub": "1955 \u2014 station archive",
   "audio": "tape_iris_audition",
   "kind": "tape",
   "dur": 30.9,
   "img": "assets/img/c_iris.webp"
  },
  {
   "id": "c_dot_17",
   "reel": 2,
   "title": "D. Vance on #17",
   "sub": "She would not explain",
   "audio": "tape_dot_seventeen",
   "kind": "tape",
   "dur": 32.81,
   "img": "assets/img/c_dot_17.webp"
  },
  {
   "id": "c_cat17",
   "reel": 2,
   "title": "Effect #17",
   "sub": "CRATE, FALLING, LARGE",
   "audio": "cat17",
   "kind": "tape",
   "dur": 42.11,
   "img": "assets/img/c_cat17.webp"
  },
  {
   "id": "c_arch_x17",
   "reel": 2,
   "title": "What #17 is",
   "sub": "The Archivist",
   "audio": "tape_arch_x17",
   "kind": "tape",
   "dur": 48.09,
   "img": "assets/img/c_arch_x17.webp"
  },
  {
   "id": "c_arch_r3",
   "reel": 3,
   "title": "Reel three",
   "sub": "The Archivist",
   "audio": "tape_arch_r3",
   "kind": "tape",
   "dur": 48.51,
   "img": "assets/img/c_arch_r3.webp"
  },
  {
   "id": "c_dial",
   "reel": 3,
   "title": "Wire recording \u2014 22:52",
   "sub": "Police exhibit 9",
   "audio": "tape_dial",
   "kind": "tape",
   "dur": 27.37,
   "img": "assets/img/c_dial.webp"
  },
  {
   "id": "c_partyline",
   "reel": 3,
   "title": "Party line intercept",
   "sub": "Three conversations, one wire",
   "audio": "tape_partyline",
   "kind": "tape",
   "dur": 58.16,
   "img": "assets/img/c_partyline.webp"
  },
  {
   "id": "c_answering",
   "reel": 3,
   "title": "The call that was answered",
   "sub": "Halloway Bay Answering Service",
   "audio": "tape_answering",
   "kind": "tape",
   "dur": 68.28,
   "img": "assets/img/c_answering.webp"
  },
  {
   "id": "c_arch_r3c",
   "reel": 3,
   "title": "Meridian",
   "sub": "The Archivist",
   "audio": "tape_arch_r3close",
   "kind": "tape",
   "dur": 42.34,
   "img": "assets/img/c_arch_r3c.webp"
  },
  {
   "id": "c_arch_hiss",
   "reel": 4,
   "title": "Reel four",
   "sub": "The Archivist",
   "audio": "tape_arch_hiss",
   "kind": "tape",
   "dur": 40.59,
   "img": "assets/img/c_arch_hiss.webp"
  },
  {
   "id": "c_backward",
   "reel": 4,
   "title": "Unlabelled reel",
   "sub": "Found in the lining of a coat",
   "audio": "tape_backward",
   "kind": "tape",
   "dur": 86.0,
   "img": "assets/img/c_backward.webp"
  },
  {
   "id": "c_blank",
   "reel": 4,
   "title": "Reel 11 \u2014 BLANK",
   "sub": "Police notation: 'nothing on it'",
   "audio": "tape_blank",
   "kind": "tape",
   "dur": 25.13,
   "img": "assets/img/c_blank.webp"
  },
  {
   "id": "c_morse",
   "reel": 4,
   "title": "Morse chart",
   "sub": "From the station wall",
   "audio": null,
   "kind": "ref",
   "dur": 0.0,
   "img": "assets/img/c_morse.webp"
  },
  {
   "id": "c_ledger",
   "reel": 4,
   "title": "Dictation disc",
   "sub": "M. Kestrel \u2014 'file the disc'",
   "audio": "tape_ledger",
   "kind": "tape",
   "dur": 67.34,
   "img": "assets/img/c_ledger.webp"
  },
  {
   "id": "c_arch_ledger",
   "reel": 4,
   "title": "Eleven thousand five hundred",
   "sub": "The Archivist",
   "audio": "tape_arch_ledger",
   "kind": "tape",
   "dur": 42.03,
   "img": "assets/img/c_arch_ledger.webp"
  },
  {
   "id": "c_arch_r5",
   "reel": 5,
   "title": "Reel five",
   "sub": "The Archivist",
   "audio": "tape_arch_r5",
   "kind": "tape",
   "dur": 60.71,
   "img": "assets/img/c_arch_r5.webp"
  },
  {
   "id": "c_last11",
   "reel": 5,
   "title": "The eleven minutes",
   "sub": "After she stopped",
   "audio": "tape_last11",
   "kind": "tape",
   "dur": 78.68,
   "img": "assets/img/c_last11.webp"
  },
  {
   "id": "c_peggy",
   "reel": 5,
   "title": "Statement: P. Nash",
   "sub": "Understudy",
   "audio": "tape_peggy",
   "kind": "tape",
   "dur": 46.47,
   "img": "assets/img/c_peggy.webp"
  },
  {
   "id": "c_halligan2",
   "reel": 5,
   "title": "Halligan, eleven years on",
   "sub": "Off the record",
   "audio": "tape_halligan_close",
   "kind": "tape",
   "dur": 48.25,
   "img": "assets/img/c_halligan2.webp"
  },
  {
   "id": "c_kestrel",
   "reel": 5,
   "title": "M. Kestrel \u2014 press statement",
   "sub": "Recorded for broadcast",
   "audio": "tape_kestrel_interview",
   "kind": "tape",
   "dur": 62.56,
   "img": "assets/img/c_kestrel.webp"
  },
  {
   "id": "c_dot_final",
   "reel": 5,
   "title": "D. Vance, forty years later",
   "sub": "'I filed a person'",
   "audio": "tape_dot_final",
   "kind": "tape",
   "dur": 74.03,
   "img": "assets/img/c_dot_final.webp"
  },
  {
   "id": "c_arch_accuse",
   "reel": 5,
   "title": "Say it",
   "sub": "The Archivist",
   "audio": "tape_arch_accuse",
   "kind": "tape",
   "dur": 35.89,
   "img": "assets/img/c_arch_accuse.webp"
  }
 ],
 "foley": [
  {
   "id": "fx_door",
   "cat": 1,
   "object": "Slam box",
   "audio": "fx_door",
   "dur": 3.03,
   "img": "assets/img/fx_door.webp"
  },
  {
   "id": "fx_gravel",
   "cat": 2,
   "object": "Gravel tray",
   "audio": "fx_gravel",
   "dur": 4.05,
   "img": "assets/img/fx_gravel.webp"
  },
  {
   "id": "fx_glass",
   "cat": 3,
   "object": "Crash box",
   "audio": "fx_glass",
   "dur": 3.03,
   "img": "assets/img/fx_glass.webp"
  },
  {
   "id": "fx_train",
   "cat": 4,
   "object": "Whistle rig",
   "audio": "fx_train",
   "dur": 4.05,
   "img": "assets/img/fx_train.webp"
  },
  {
   "id": "fx_rain",
   "cat": 5,
   "object": "Rain drum",
   "audio": "fx_rain",
   "dur": 5.04,
   "img": "assets/img/fx_rain.webp"
  },
  {
   "id": "fx_horse",
   "cat": 6,
   "object": "Coconut hooves",
   "audio": "fx_horse",
   "dur": 4.05,
   "img": "assets/img/fx_horse.webp"
  },
  {
   "id": "fx_wind",
   "cat": 7,
   "object": "Wind machine",
   "audio": "fx_wind",
   "dur": 5.04,
   "img": "assets/img/fx_wind.webp"
  },
  {
   "id": "fx_birdcage",
   "cat": 8,
   "object": "Birdcage",
   "audio": "fx_birdcage",
   "dur": 3.03,
   "img": "assets/img/fx_birdcage.webp"
  },
  {
   "id": "fx_thunder",
   "cat": 9,
   "object": "Thunder sheet",
   "audio": "fx_thunder",
   "dur": 5.04,
   "img": "assets/img/fx_thunder.webp"
  },
  {
   "id": "fx_cabbage",
   "cat": null,
   "object": "Cabbage & knife",
   "audio": "fx_cabbage",
   "dur": 3.03,
   "img": "assets/img/fx_cabbage.webp"
  }
 ],
 "locks": [
  {
   "id": "lock1",
   "reel": 1,
   "type": "keypad",
   "length": 3,
   "answer": "492",
   "title": "Reel canister \u2014 3-digit dial",
   "prompt": "Three effects play under the final scene. Dot numbered every effect in that building. Their numbers, in the order you hear them.",
   "unlocks_reel": 2
  },
  {
   "id": "lock2a",
   "reel": 2,
   "type": "sequence",
   "answer": [
    "fx_rain",
    "fx_door",
    "fx_gravel",
    "fx_wind",
    "fx_glass"
   ],
   "pool": [
    "fx_rain",
    "fx_door",
    "fx_gravel",
    "fx_wind",
    "fx_glass",
    "fx_thunder",
    "fx_horse",
    "fx_birdcage",
    "fx_cabbage"
   ],
   "title": "Rebuild scene 3",
   "prompt": "Five objects from the Foley room made that scene. Lay them out in the order they were played."
  },
  {
   "id": "lock2b",
   "reel": 2,
   "type": "choice",
   "answer": "cat17",
   "options": [
    {
     "id": "fx_thunder",
     "label": "Thunder sheet"
    },
    {
     "id": "fx_glass",
     "label": "Crash box"
    },
    {
     "id": "cat17",
     "label": "Effect #17"
    },
    {
     "id": "fx_cabbage",
     "label": "Cabbage & knife"
    },
    {
     "id": "fx_horse",
     "label": "Coconut hooves"
    }
   ],
   "title": "The sixth element",
   "prompt": "As transmitted, that scene had six sounds in it, not five. One of them was never made in that room. Which?",
   "unlocks_reel": 3
  },
  {
   "id": "lock3",
   "reel": 3,
   "type": "keypad",
   "length": 7,
   "answer": "6305274",
   "title": "Place the call",
   "prompt": "Count the pulses. One click is a 1. Ten clicks is a 0.",
   "unlocks_card": "c_answering",
   "unlocks_reel": 4
  },
  {
   "id": "lock4",
   "reel": 4,
   "type": "keypad",
   "length": 4,
   "answer": "1103",
   "title": "Kestrel's safe \u2014 4 digits",
   "prompt": "Behind the Nocturne plaque. Dot left the number where she leaves everything: above where anybody thinks to listen.",
   "unlocks_card": "c_ledger",
   "unlocks_reel": 5
  },
  {
   "id": "lock5",
   "reel": 5,
   "type": "accusation",
   "title": "The accusation",
   "parts": [
    {
     "id": "who",
     "question": "Who took Vera Lyle out of Studio A?",
     "options": [
      "vera",
      "kestrel",
      "dot",
      "eddie",
      "doyle",
      "peggy",
      "halligan"
     ],
     "answer": "vera"
    },
    {
     "id": "what",
     "question": "What is really on effect #17?",
     "options": [
      "crate",
      "storm",
      "iris_death",
      "vera_death",
      "nothing"
     ],
     "labels": {
      "crate": "A wooden crate falling",
      "storm": "A thunder rig collapsing",
      "iris_death": "The death of Iris Bell",
      "vera_death": "The death of Vera Lyle",
      "nothing": "Nothing \u2014 the reel is blank"
     },
     "answer": "iris_death"
    },
    {
     "id": "killer",
     "question": "Who killed Iris Bell?",
     "options": [
      "vera",
      "kestrel",
      "dot",
      "eddie",
      "doyle",
      "peggy",
      "halligan"
     ],
     "answer": "kestrel"
    }
   ]
  }
 ],
 "suspects": [
  {
   "id": "vera",
   "name": "Vera Lyle",
   "role": "The star. Vanished."
  },
  {
   "id": "kestrel",
   "name": "Marlow Kestrel",
   "role": "Station owner."
  },
  {
   "id": "dot",
   "name": "Dorothy Vance",
   "role": "Foley artist."
  },
  {
   "id": "eddie",
   "name": "Eddie Ferris",
   "role": "Board engineer."
  },
  {
   "id": "doyle",
   "name": "Cal Doyle",
   "role": "Meridian Broadcast Holdings."
  },
  {
   "id": "peggy",
   "name": "Peggy Nash",
   "role": "Understudy."
  },
  {
   "id": "halligan",
   "name": "Det. Halligan",
   "role": "Investigating officer."
  }
 ],
 "coda": {
  "id": "coda",
  "target_speed": 1.282,
  "tolerance": 0.055,
  "tracks": [
   "tape_arch_open",
   "tape_arch_accuse",
   "tape_end_correct"
  ],
  "reveal": "tape_epilogue"
 },
 "hints": {
  "1": [
   "tape_hint_r1_1",
   "tape_hint_r1_2",
   "tape_hint_r1_3"
  ],
  "2": [
   "tape_hint_r2_1",
   "tape_hint_r2_2",
   "tape_hint_r2_3"
  ],
  "3": [
   "tape_hint_r3_1",
   "tape_hint_r3_2",
   "tape_hint_r3_3"
  ],
  "4": [
   "tape_hint_r4_1",
   "tape_hint_r4_2",
   "tape_hint_r4_3"
  ],
  "5": [
   "tape_hint_r5_1",
   "tape_hint_r5_2",
   "tape_hint_r5_3"
  ]
 },
 "durations": {
  "tape_broadcast": 118.83,
  "tape_warped": 14.21,
  "tape_eddie": 64.5,
  "tape_halligan": 53.76,
  "tape_index": 87.77,
  "tape_scene88": 26.04,
  "cat17": 42.11,
  "tape_iris_audition": 30.9,
  "tape_dot_interview": 52.95,
  "tape_dot_seventeen": 32.81,
  "tape_dial": 27.37,
  "tape_answering": 68.28,
  "tape_partyline": 58.16,
  "tape_backward": 86.0,
  "tape_blank": 25.13,
  "tape_ledger": 67.34,
  "tape_last11": 78.68,
  "tape_peggy": 46.47,
  "tape_halligan_close": 48.25,
  "tape_kestrel_interview": 62.56,
  "tape_dot_final": 74.03,
  "tape_scene88x": 57.1,
  "tape_arch_open": 94.46,
  "tape_arch_console": 62.46,
  "tape_arch_r2": 57.84,
  "tape_arch_x17": 48.09,
  "tape_arch_r3": 48.51,
  "tape_arch_r3close": 42.34,
  "tape_arch_hiss": 40.59,
  "tape_arch_ledger": 42.03,
  "tape_arch_r5": 60.71,
  "tape_arch_accuse": 35.89,
  "tape_arch_lockhint": 38.24,
  "tape_end_correct": 152.82,
  "tape_end_wrong": 62.25,
  "tape_end_partial": 44.59,
  "tape_epilogue": 55.72,
  "tape_hint_r1_1": 13.43,
  "tape_hint_r1_2": 15.57,
  "tape_hint_r1_3": 16.2,
  "tape_hint_r2_1": 13.74,
  "tape_hint_r2_2": 13.74,
  "tape_hint_r2_3": 10.97,
  "tape_hint_r3_1": 14.97,
  "tape_hint_r3_2": 16.3,
  "tape_hint_r3_3": 7.89,
  "tape_hint_r4_1": 11.47,
  "tape_hint_r4_2": 14.34,
  "tape_hint_r4_3": 13.74,
  "tape_hint_r5_1": 13.01,
  "tape_hint_r5_2": 14.65,
  "tape_hint_r5_3": 16.09,
  "tape_sys_lock_open": 3.06,
  "tape_sys_lock_fail": 3.53,
  "tape_sys_reel_loaded": 3.94,
  "tape_sys_card_new": 4.05,
  "fx_door": 3.03,
  "fx_gravel": 4.05,
  "fx_glass": 3.03,
  "fx_train": 4.05,
  "fx_rain": 5.04,
  "fx_horse": 4.05,
  "fx_wind": 5.04,
  "fx_birdcage": 3.03,
  "fx_thunder": 5.04,
  "fx_cabbage": 3.03,
  "crash": 6.03,
  "syn_dial": 15.31,
  "syn_morse": 23.64,
  "syn_beep": 0.5,
  "syn_linenoise": 12.04,
  "syn_hiss": 12.04
 },
 "archivistRate": 0.78
};
