package dev.syndata.insert;

import dev.syndata.db.Db;
import dev.syndata.model.ColumnModel;
import dev.syndata.model.DataSetModel;
import dev.syndata.model.SchemaModel;
import dev.syndata.model.TableDataModel;
import dev.syndata.model.TableModel;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.io.Writer;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

/**
 * Renders a generated data set to a plain SQL script that any client (psql,
 * IDE, migration tool) can run — no syndata needed on the target machine.
 *
 * <p>Sequence-backed ids are resolved inside the script itself: a temporary
 * mapping table is filled with {@code nextval()} calls, and inserts look real
 * ids up through scalar subqueries. The whole script is one transaction.</p>
 */
public class SqlScriptExporter {

    private static final String IDS = "_syndata_ids";
    private static final int ROWS_PER_INSERT = 100;

    private final SchemaModel schema;
    private final DataSetModel data;

    public SqlScriptExporter(SchemaModel schema, DataSetModel data) {
        this.schema = schema;
        this.data = data;
    }

    public int export(Path out) {
        int total = 0;
        try (Writer w = Files.newBufferedWriter(out)) {
            w.write("-- Generated by syndata" + (data.seed != null ? " (seed " + data.seed + ")" : "") + "\n");
            w.write("begin;\n\n");
            w.write("create temporary table " + IDS
                    + " (local_id bigint primary key, real_id bigint not null) on commit drop;\n");

            for (TableDataModel tableData : data.tables) {
                TableModel table = requireTable(tableData.name);
                writeIdAllocations(w, table, tableData);
            }
            w.write("\n");
            List<String> updates = new ArrayList<>();
            for (TableDataModel tableData : data.tables) {
                TableModel table = requireTable(tableData.name);
                total += writeInserts(w, table, tableData, updates);
            }
            if (!updates.isEmpty()) {
                w.write("-- deferred FK columns (dependency cycles)\n");
                for (String update : updates) {
                    w.write(update);
                    w.write("\n");
                }
                w.write("\n");
            }
            w.write("commit;\n");
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot write " + out, e);
        }
        return total;
    }

    private TableModel requireTable(String name) {
        TableModel table = schema.table(name);
        if (table == null) {
            throw new IllegalArgumentException("Table '" + name
                    + "' from the data file is not present in the schema file.");
        }
        return table;
    }

    /** Fills the mapping table with one nextval() per local id of this table. */
    private void writeIdAllocations(Writer w, TableModel table, TableDataModel data) throws IOException {
        for (int c = 0; c < data.columns.size(); c++) {
            ColumnModel col = table.column(data.columns.get(c));
            if (col == null || col.sequence == null) {
                continue;
            }
            List<Long> localIds = new ArrayList<>();
            for (List<Object> row : data.rows) {
                if (row.get(c) instanceof Number n && n.longValue() < 0) {
                    localIds.add(n.longValue());
                }
            }
            for (int from = 0; from < localIds.size(); from += 1000) {
                List<Long> chunk = localIds.subList(from, Math.min(from + 1000, localIds.size()));
                w.write("insert into " + IDS + " (local_id, real_id)\n  select x, nextval('"
                        + Db.quoteQualified(col.sequence) + "') from unnest(array["
                        + chunk.stream().map(String::valueOf).collect(Collectors.joining(","))
                        + "]) as x;\n");
            }
        }
    }

    private int writeInserts(Writer w, TableModel table, TableDataModel data,
                             List<String> updates) throws IOException {
        if (data.rows.isEmpty()) {
            return 0;
        }
        List<ColumnModel> cols = new ArrayList<>();
        for (String name : data.columns) {
            ColumnModel col = table.column(name);
            if (col == null) {
                throw new IllegalArgumentException("Column " + table.name + "." + name
                        + " from the data file is not present in the schema file.");
            }
            cols.add(col);
        }
        boolean[] remap = new boolean[cols.size()];
        boolean[] deferred = new boolean[cols.size()];
        for (int i = 0; i < cols.size(); i++) {
            remap[i] = cols.get(i).sequence != null
                    || DataInserter.referencesSequencedColumn(schema, table, cols.get(i).name);
            deferred[i] = data.deferredFkColumns.contains(cols.get(i).name);
        }
        int pkIdx = table.primaryKey.size() == 1 ? data.columns.indexOf(table.primaryKey.get(0)) : -1;

        String target = Db.quote(table.schema) + "." + Db.quote(table.name);
        String header = "insert into " + target + " ("
                + data.columns.stream().map(Db::quote).collect(Collectors.joining(", ")) + ")"
                + (cols.stream().anyMatch(c -> c.identityAlways) ? " overriding system value" : "")
                + " values\n";

        for (int from = 0; from < data.rows.size(); from += ROWS_PER_INSERT) {
            w.write(header);
            int to = Math.min(from + ROWS_PER_INSERT, data.rows.size());
            for (int r = from; r < to; r++) {
                List<Object> row = data.rows.get(r);
                StringBuilder line = new StringBuilder("  (");
                for (int i = 0; i < cols.size(); i++) {
                    if (i > 0) {
                        line.append(", ");
                    }
                    Object value = row.get(i);
                    if (deferred[i]) {
                        if (value != null && pkIdx >= 0) {
                            updates.add("update " + target + " set " + Db.quote(cols.get(i).name)
                                    + " = " + render(cols.get(i), value, true)
                                    + " where " + Db.quote(cols.get(pkIdx).name)
                                    + " = " + render(cols.get(pkIdx), row.get(pkIdx), remap[pkIdx]) + ";");
                        }
                        line.append("NULL");
                    } else {
                        line.append(render(cols.get(i), value, remap[i]));
                    }
                }
                line.append(r == to - 1 ? ");" : "),");
                w.write(line.toString());
                w.write("\n");
            }
            w.write("\n");
        }
        return data.rows.size();
    }

    /** Renders one value as a SQL literal, or as an id-mapping subquery for local ids. */
    static String render(ColumnModel col, Object value, boolean remap) {
        if (value == null) {
            return "NULL";
        }
        if (value instanceof Number n) {
            if (remap && n.longValue() < 0) {
                return "(select real_id from " + IDS + " where local_id = " + n.longValue() + ")";
            }
            return value instanceof BigDecimal bd ? bd.toPlainString() : n.toString();
        }
        if (value instanceof Boolean b) {
            return b.toString();
        }
        String type = col.typeName.toLowerCase(Locale.ROOT);
        String s = value.toString();
        if (type.equals("bytea")) {
            byte[] bytes = value instanceof byte[] raw ? raw : Base64.getDecoder().decode(s);
            return "'\\x" + HexFormat.of().formatHex(bytes) + "'";
        }
        return "'" + s.replace("'", "''") + "'";
    }
}
