-- Runs once on first startup of the postgres container (empty data volume).
-- The database "appdb" and user "app" are already created by the official
-- image from the POSTGRES_* environment variables in docker-compose.yml.
-- The application schema itself is generated by Hibernate
-- (schema-generation.database.action=update in persistence.xml).

-- Add any extensions or seed data your project needs, e.g.:
-- CREATE EXTENSION IF NOT EXISTS pgcrypto;
