"""Build everything: voice, effects, score, synthesis, composites, data.js.

    python3 tools/build.py            # full build (cached; cheap to re-run)
    python3 tools/build.py --no-api   # assemble only, from what's already cached
"""
import json
import os
import sys

import case
import synth
import assemble
from common import AUDIO, GAME, ROOT, log, duration
from script_text import LINES
from voices import VOICES

NO_API = "--no-api" in sys.argv


def main():
    speakers = {lid: sp for lid, (sp, _) in LINES.items()}

    # ── 1. voice ───────────────────────────────────────────────────────────
    if NO_API:
        from common import RAW
        vo = {lid: os.path.join(RAW, "vo_%s.mp3" % lid) for lid in LINES}
        vo = {k: v for k, v in vo.items() if os.path.exists(v)}
        missing = set(LINES) - set(vo)
        if missing:
            raise SystemExit("--no-api but %d lines are not cached: %s"
                             % (len(missing), sorted(missing)[:5]))
    else:
        import gen_voice
        vo = gen_voice.generate(LINES)

    # ── 2. effects and score ───────────────────────────────────────────────
    if NO_API:
        from common import RAW
        sf = {}
        for aid in list(case.FOLEY) + list(case.SFX) + ["crash"]:
            p = os.path.join(RAW, "sfx_%s.mp3" % aid)
            if os.path.exists(p):
                sf[aid] = p
        for aid in case.MUSIC:
            p = os.path.join(RAW, "mus_%s.mp3" % aid)
            if os.path.exists(p):
                sf[aid] = p
    else:
        import gen_sfx
        sf = gen_sfx.generate(case.FOLEY, case.SFX, case.CRASH_17, case.MUSIC)

    # ── 3. procedural puzzle audio ─────────────────────────────────────────
    log("── synthesising puzzle audio")
    sy = synth.build_all(case.SYNTH)

    # ── 4. the Foley object cards (same files the montages use) ────────────
    lib = assemble.export_library(case.FOLEY, sf)

    sources = {}
    sources.update(vo)
    sources.update(sf)
    sources.update(sy)

    # ── 5. composites + narration ──────────────────────────────────────────
    hint_tapes = {}
    for reel, ids in case.HINTS.items():
        for h in ids:
            hint_tapes["tape_" + h] = (h, "worn", None)
    sys_tapes = {"tape_" + k: (k, "clean", None)
                 for k in LINES if k.startswith("sys_")}

    simple = dict(case.SIMPLE_TAPES)
    simple.update(hint_tapes)
    simple.update(sys_tapes)

    durations = assemble.build_all(case.COMPOSITES, simple, sources, speakers)
    for aid, p in list(lib.items()) + list(sy.items()):
        durations[aid] = duration(p)

    # ── 6. emit data.js ────────────────────────────────────────────────────
    emit(durations)
    log("── build complete")


def emit(durations):
    cards = []
    for c in case.CARDS:
        d = dict(c)
        d["dur"] = round(durations.get(c["audio"], 0.0), 2) if c["audio"] else 0.0
        d.pop("art", None)
        d["img"] = "assets/img/%s.webp" % c["id"]
        cards.append(d)

    foley_cards = []
    for aid, f in case.FOLEY.items():
        foley_cards.append(dict(
            id=aid, cat=f["cat"], object=f["object"],
            audio=aid, dur=round(durations.get(aid, 0.0), 2),
            img="assets/img/%s.webp" % aid))

    data = dict(
        title="The Nocturne Tapes",
        reels=case.REELS,
        cards=cards,
        foley=foley_cards,
        locks=case.LOCKS,
        suspects=case.SUSPECTS,
        coda=case.CODA,
        hints={str(k): ["tape_" + h for h in v] for k, v in case.HINTS.items()},
        durations={k: round(v, 2) for k, v in durations.items()},
        archivistRate=0.78,
    )
    out = os.path.join(GAME, "data.js")
    with open(out, "w") as f:
        f.write("// Generated by tools/build.py — do not edit by hand.\n")
        f.write("window.CASE = ")
        json.dump(data, f, indent=1)
        f.write(";\n")
    log("   wrote", os.path.relpath(out, ROOT))

    n = len([f for f in os.listdir(AUDIO) if f.endswith(".mp3")])
    mb = sum(os.path.getsize(os.path.join(AUDIO, f))
             for f in os.listdir(AUDIO)) / 1e6
    log("   %d audio files, %.1f MB" % (n, mb))


if __name__ == "__main__":
    main()
